### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by QuoFata** [ramack/exiftool_gps#1]
<b>Warning</b>:  **shell_exec() has been disabled for security reasons in** <b>/.../plugins/exiftool_keywords/main.inc.php</b> on line <b>19</b><br />
<br />
<b>Warning</b>:  **shell_exec() has been disabled for security reasons in** <b>/.../plugins/exiftool_gps/main.inc.php</b> on line <b>20</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/.../plugins/exiftool_gps/main.inc.php</b> on line <b>23</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /.../plugins/exiftool_keywords/main.inc.php:19) in <b>/.../include/page_header.php</b> on line <b>101</b><br />

**Comment by ramack** [comment]
Thanks for this report. It would be even nicer, if you would not just throw a set of warnings but also include some friendly text - chances are much better to get help in that case...

For sure you could find that also via your favorite search engine, but it looks, as you (or your hosting provider) has disabled the use of the php function shell_exec() via php.ini, directive disable_functions. You could validate using phpinfo(). But even if you make your hoster enable it, the next question that will arise is whether exiftool is installed - maybe you raise it before making noise...

I hope it helps.
