### ISSUE TITLE
Warning when activating piwigo_privacy

### ISSUE THREAD

**Issue by efelon** [ramack/exiftool_gps#6]
Piwigo 2.9.4
Operating system: Linux
PHP: 7.0.33-0+deb9u1 (Show info) [2018-12-25 00:33:32]
MySQL: 5.5.5-10.1.37-MariaDB-0+deb9u1 [2018-12-25 00:33:32]
Graphics Library: ImageMagick 6.9.7-4

After activating piwigo_privacy (http://piwigo.org/ext/extension_view.php?eid=849) without changing anything in the nginx configuration i get following above every image page:

```
Warning: Invalid argument supplied for foreach() in /var/www/piwigo/plugins/exiftool_gps/main.inc.php on line 23
```

**Comment by ramack** [comment]
For me this looks like being independent from piwigo_privacy and the same as #2.
Do you see anything I miss?

**Comment by dgrammlich** [comment]
Hi @ramack, 
I ran into the same issue. It is related to the filepath used in the script:
```
$ exiftool -json "././plugins/piwigo_privacy/get.php?img_id=562&file=./upload/2019/08/28/20190828150347-9749bc68.jpg"
File not found: ././plugins/piwigo_privacy/get.php?img_id=562&file=./upload/2019/08/28/20190828150347-9749bc68.jpg
```
and with missing metadata the `foreach` fails. 
Using the absolute path to the picture shows:
```
$ exiftool -json "/var/www/html/_data/i/upload/2019/08/28/20190828150347-9749bc68-me.jpg"
[{
  "SourceFile": "/var/www/html/_data/i/upload/2019/08/28/20190828150347-9749bc68-me.jpg",
  "ExifToolVersion": 11.01,
  "FileName": "20190828150347-9749bc68-me.jpg",
  ...
```
I didn't look further. Maybe you can help me with this.

Cheers
Daniela

My Piwigo stats:
>     Piwigo 2.9.5
>     Betriebssystem: Linux
>     PHP: 7.3.9 (Info anzeigen) [2019-09-26 09:09:37]
>     MySQL: 5.5.5-10.3.18-MariaDB [2019-09-26 09:09:37]
>     Grafikbibliothek: External ImageMagick 6.9.7-4

**Comment by ramack** [comment]
sorry for the late response.
@dgrammlich do I understand this correctly that with piwigo_privacy active photo paths passed into eg_format_exif_data are somehow modified?
@yonjah do you as the author of piwigo_privacy understand what's going on here and why the photopath is so strange?

**Comment by ramack** [comment]
another question: In your case

**Comment by yonjah** [comment]
@ramack I suggest we'll move discussion to the piwigo_privacy issue so it will be easier to follow -
yonjah/piwigo_privacy#17
